name: nodetest
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  js:
  node_interop:

dev_dependencies:
  cli_pkg:
  grinder:
  node_preamble:
